apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-capstone-app
  labels:
    app: eks-capstone-app
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: eks-capstone-app
  strategy:
    rollingUpdate:
      maxSurge: 20%
      maxUnavailable: 20%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: eks-capstone-app
    spec:
      containers:
        - image: cchaduka/eks-capstone-app
          imagePullPolicy: Always
          name: eks-capstone-app
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: eks-capstone-app
  labels:
    app: eks-capstone-app
spec:
  type: LoadBalancer
  selector:
    app: eks-capstone-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
      protocol: TCP